steps:
  - id: Sync static web files
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gsutil
    args: ['-h', 'Cache-Control:public, max-age=15', 'cp', '-r', 'web/*', 'gs://aoe-stats.davidbraden.co.uk']
